name: '🧪 and 📢 and 📲'

on:
  push:
    branches: ['main']
jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: dyne/pnpm@main
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: |
          git clone --recursive https://github.com/forkbombeu/signroom
          cd signroom/admin
          mkdir pb_data
          cp ../../tests/fixtures/test.db pb_data/data.db
          go build
          ./pb migrate
          ./pb serve &
      - run: npx playwright install --with-deps
      - run: pnpm test:integration
        env:
          PUBLIC_BACKEND_URL: http://localhost:8090
          USER_EMAIL: ${{ vars.USER_EMAIL }}
          USER_PASSWORD: ${{ vars.USER_PASSWORD }}
          USER_SEED: ${{ vars.USER_SEED }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 10

  distribute:
    runs-on: ubuntu-latest
    environment: test
    # needs: tests
    steps:
      - uses: dyne/pnpm@main
        with:
          submodules: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'
      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: android_keystore.keystore
          encodedString: ${{ secrets.ANDROID_KEYSTORE_FILE }}      
      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: playstore_keystore
        with:
          fileName: android_keystore.keystore
          encodedString: ${{ secrets.BUNDLE_BETA_PLAYSTORE }}
      - name: Decode Service Account File for Firebase
        uses: timheuer/base64-to-file@v1
        id: service_account
        with:
          fileName: play-store-credentials.json
          encodedString: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Decode Service Account File for PlayStore
        uses: timheuer/base64-to-file@v1
        id: play_console_account
        with:
          fileName: play-store-credentials.json
          encodedString: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - uses: maierj/fastlane-action@v3.1.0
        env:
          KEYSTORE_PATH: ${{ steps.playstore_keystore.outputs.filePath }}
          SERVICE_ACCOUNT_PATH: ${{ steps.play_console_account.outputs.filePath }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.BUNDLE_BETA_PLAYSTORE_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.BUNDLE_BETA_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.BUNDLE_BETA_PASSWORD }}
        with:
          lane: alpha
