name: 🤖🎯 Droid Beta Launchpad

on:
  push:
    branches: ['stable']

jobs:
  distribute:
    uses: ForkbombEu/ship-capacitor-apps/.github/workflows/ship_android.yml@main
    with:
      backend-url: ${{ vars.PUBLIC_BACKEND_URL }}
      lane: beta
      package-name: com.didroom.wallet
    secrets:
      keystore-file: ${{ secrets.BUNDLE_BETA_PLAYSTORE }}
      service-account: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}
      keystore-alias: ${{ secrets.BUNDLE_BETA_PLAYSTORE_ALIAS }}
      keystore-password: ${{ secrets.BUNDLE_BETA_PASSWORD }}
      keystore-key-password: ${{ secrets.BUNDLE_BETA_PASSWORD }}
