name: '🧪 and 📢 and 📲'

on:
  pull_request:
    branches: ['main']

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - uses: dyne/pnpm@main
        with:
          submodules: true
      - run: npx playwright install --with-deps
      - run: pnpm test:integration
        env:
          PUBLIC_BACKEND_URL: ${{ vars.PUBLIC_BACKEND_URL }}
          USER_EMAIL: ${{ vars.USER_EMAIL }}
          USER_PASSWORD: ${{ vars.USER_PASSWORD }}
          USER_SEED: ${{ vars.USER_SEED }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 10

  distribute:
    runs-on: ubuntu-latest
    environment: test
    needs: tests
    steps:
      - uses: dyne/pnpm@main
        with:
          submodules: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'
      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: android_keystore.keystore
          encodedString: ${{ secrets.ANDROID_KEYSTORE_FILE }}
      - name: Decode Service Account File
        uses: timheuer/base64-to-file@v1
        id: service_account
        with:
          fileName: play-store-credentials.json
          encodedString: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - uses: maierj/fastlane-action@v3.1.0
        env:
          KEYSTORE_PATH: ${{ steps.android_keystore.outputs.filePath }}
          SERVICE_ACCOUNT_PATH: ${{ steps.service_account.outputs.filePath }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
        with:
          lane: distribute
