name: 🔥📲 Droid FireDrop

on:
  pull_request:
    branches: ['main']

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    with:
      backend-url: http://127.0.0.1:8090
      user-email: ${{ vars.USER_EMAIL }}
      user-password: ${{ vars.USER_PASSWORD }}
      user-seed: ${{ vars.USER_SEED }}

  distribute:
    uses: ./.github/workflows/ship_android.yml
    needs: tests
    with:
      backend-url: ${{ github.env.test.vars.PUBLIC_BACKEND_URL }}
      lane: distribute
    secrets:
      keystore-file: ${{ secrets.ANDROID_KEYSTORE_FILE }}
      service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      keystore-alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      keystore-password: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
      keystore-key-password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      firebase-app-id: ${{ secrets.FIREBASE_APP_ID }}
