name: 🚀🌍 Universal Stardust Release

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform(s) to build'
        required: true
        default: 'both'
        type: choice
        options:
          - android
          - ios
          - both

jobs:
  distribute_android:
    if: ${{ github.ref == 'refs/heads/stable'&&(github.event.inputs.platform == 'android' || github.event.inputs.platform == 'both') }}
    uses: ForkbombEu/ship-capacitor-apps/.github/workflows/ship_android.yml@main
    with:
      backend-url: ${{ vars.PUBLIC_BACKEND_URL }}
      lane: production
      package-name: com.didroom.wallet
    secrets:
      keystore-file: ${{ secrets.BUNDLE_BETA_PLAYSTORE }}
      service-account: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}
      keystore-alias: ${{ secrets.BUNDLE_BETA_PLAYSTORE_ALIAS }}
      keystore-password: ${{ secrets.BUNDLE_BETA_PASSWORD }}
      keystore-key-password: ${{ secrets.BUNDLE_BETA_PASSWORD }}

  distribute_ios:
    if: ${{ github.ref == 'refs/heads/stable'&&(github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'both') }}
    uses: ForkbombEu/ship-capacitor-apps/.github/workflows/ship_ios.yml@main
    with:
      backend-url: ${{ vars.PUBLIC_BACKEND_URL }}
      lane: ios production
      DEMO_USER: ${{ github.env.ios.vars.USER_EMAIL }}
      DEMO_PASSWORD: ${{ github.env.ios.vars.USER_PASSWORD }}
      CONTACT_EMAIL: info@forkbomb.eu
      CONTACT_FIRST_NAME: Andrea
      CONTACT_LAST_NAME: D'Intino
      CONTACT_PHONE: "+4521627918"
      package-name: com.didroom.wallet
    secrets:
      APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
      BUNDLE_IDENTIFIER: ${{ secrets.BUNDLE_IDENTIFIER }}
      BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_BUILD_CERTIFICATE }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_BUILD_PROVISION_PROFILE }}
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
      APPLE_PROFILE_NAME: ${{ secrets.APPLE_PROFILE_NAME }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
