name: Reusable Tests Workflow

on:
  workflow_call:
    inputs:
      backend-url:
        required: true
        type: string
      user-email:
        required: true
        type: string
      user-password:
        required: true
        type: string
      user-seed:
        required: true
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: dyne/pnpm@main
        with:
          node-version: '20.11.1'
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/dyne/Zenroom/releases/download/v5.20.0/zencode-exec
          name: zencode-exec
          version: '5.20.0'
      - run: |
          git clone --recursive https://github.com/forkbombeu/signroom
          cd signroom/admin
          mkdir pb_data
          cp ../../tests/fixtures/test.db pb_data/data.db
          rm pb_migrations/1685000000_seed_features.js
          go build
          ./pb migrate
          ./pb serve &
      - run: npx playwright install --with-deps
      - run: pnpm test:integration --workers 1
        env:
          PUBLIC_BACKEND_URL: ${{ inputs.backend-url }}
          USER_EMAIL: ${{ inputs.user-email }}
          USER_PASSWORD: ${{ inputs.user-password }}
          USER_SEED: ${{ inputs.user-seed }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 10
